config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/search' => 'groups#search'

  get '/groups' => 'groups#discover'
  
  resources :users do 
    resources :groups, only: [:new, :create, :index]
  end
  
  resources :groups do 
    resources :topics
  end
  resources :topics

  resources :meetings
  
  resources :groups do
    resources :meetings
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :user
    belongs_to :group
    
    validates :title, presence: true
    validates :group, uniqueness: {scope: :user_id, message: "Only one Topic per user allowed."}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_topic, only: [:show, :edit, :update]
    
    def index
        if params[:group_id] && @group = Group.find_by_id(params[:group_id])
           @topics = @group.topics
        else
          @error = "That group doesn't exist" if params[:group_id]
          @topics = Topic.all
        end
    end

    def new
        if params[:group_id] && @group = Group.find_by_id(params[:group_id])
            @topic = @group.topics.build
            @groups = Group.all.my_groups(current_user.id)
          else
            @error = "That group doesn't exist" if params[:group_id]
            @topic = Topic.new
          end
    end
      
    def create
      if params[:group_id] && @group = Group.find_by_id(params[:group_id])
        @topic = current_user.topics.build(topic_params)
        if @topic.save
            redirect_to group_topics_path
        else
            render :new
        end
      else
        redirect_to '/'
      end
    end

    def edit
    end

    def show
    end

    def update
        if @topic.update(topic_params)
          redirect_to topic_path(@topic)
        else
          render :edit
        end
    end

    def destroy
        @topic = Topic.find(params[:id])
        if @topic.user == current_user
          @topic.destroy
          redirect_to topics_url
        else
          render :show
        end
    end

    private

    def topic_params
        params.require(:topic).permit(:title,:group_id)
    end

    def set_topic
        @topic = Topic.find_by(id: params[:id])
        if !@topic
          flash[:message] = "Topic was not found"
          redirect_to topics_path
        end
    end

end

app/views/topics/_topics.html.erb
<ul>
<% @topics.each do |topic|%>
  <li><strong><%= link_to topic.title, topic_path(topic) %></strong> - Created by: <b><%= topic.user.username%></b> for Group: <b> <%=topic.group.title%> </b></li><br><br>
<% end %>
</ul>

app/views/topics/edit.html.erb
<h1>Edit Topic:</h1>

<%= render partial: "layouts/errors", locals: {object: @topic} %>

<%= form_for(@topic) do |f|%>

  <%= f.label :group %>
  <%= f.collection_select :group_id, Group.all, :id, :title %>

  <%= f.label :title %>
  <%= f.text_field :title %>


  <%= f.submit %>

<% end %>

app/views/topics/index.html.erb
<% if @group %>
  <h1>Topics:</h1>
<% else %>
  <h1>Topic Discovery</h1>
<% end %>

<%= render partial: "topics", locals: {object: @topics} %>

app/views/topics/new.html.erb
<% if @topic.group %>
    <h1>New Topic for <%= @topic.group.title%>!</h1>
<% else %>
    <h1>New Topic!</h1>
<% end %>

<%= render partial: "layouts/errors", locals: {object: @topic} %>

<%= form_for([@topic.group,@topic]) do |f|%>

 <% if !@topic.group %>
  <%= f.label :group %>
  <%= f.collection_select :group_id, @groups, :id, :title %>
<% else %>
    <%= f.hidden_field :group_id %>
<% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>


  <%= f.submit %>

<% end %>

app/views/topics/show.html.erb
<h2><%= @topic.title %> - <%= @topic.user.username%></h2>

<% if @topic.user == current_user %>
  <%= link_to "Edit Topic", edit_topic_path(@topic)%>
  <%= link_to 'Delete', @topic, method: :delete, data: { confirm: 'Are you sure?' } %><br>
<% end %>