config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/search' => 'groups#search'

  get '/groups' => 'groups#discover'
  
  resources :users do 
    resources :groups, only: [:new, :create, :index]
  end
  
  resources :groups do 
    resources :topics
  end
  resources :topics

  resources :meetings
  
  resources :groups do
    resources :meetings
  end
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    has_many :topics
    has_many :users, through: :topics

    has_many :meetings

    validates :title, :description, :rules, presence: true

    scope :my_groups, -> (user_id) {
        where(
            "id IN ( SELECT user_id 
            FROM groups
            WHERE user_id = ?
          )",
   user_id 
        )
    }

    scope :search, -> (title) {
        where(
            "title IN ( SELECT title
            FROM groups
            WHERE title = ?
        )",
    title
        )
    }

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

    before_action :redirect_if_not_logged_in

    def new
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            if current_user
                @group = @user.groups.build
            end
        else
            redirect_to groups_path
        end
    end

    def create
        @group = current_user.groups.build(group_params)
        if @group.save
            redirect_to groups_path
        else
            render :new
        end
    end

    def edit
        @group = Group.find_by_id(params[:id])
        redirect_to groups_path if !@group || @group.user != current_user
    end

    def update
        @group = Group.find_by(id: params[:id])
        redirect_to groups_path if !@group || @group.user != current_user
       if @group.update(group_params)
         redirect_to group_path(@group)
       else
         render :edit
       end
     end

    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @groups = @user.groups
        else
            flash[:message] = "That group does not exist!" if params[:user_id]
            @groups = Group.all.my_groups(current_user.id)
        end
    end

    def discover
        @groups = Group.all
    end

    def show
        @group = Group.find(params[:id])
        redirect_to '/' if !@group
    end

    def search
        @all_groups = Group.all
        @groups = @all_groups.search(params[:query])
    end

    private

    def group_params
        params.require(:group).permit(:title, :description, :rules)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_groups.html.erb
<%= form_for(@group) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <br>

    <%= f.label :description %>
    <%= f.text_field :description %>
    <br>
    <br>

    <%= f.label :rules %>
    <%= f.text_field :rules %>
    <br>
    <br>

    <%= f.submit %>
<% end %>

app/views/groups/discover.html.erb
<h1>Groups</h1>

<ul>
<% @groups.each do |group| %>


        <li> Title: <%= link_to group.title, group_path(group) %> - Created by: <%= group.user.username%></li><br><br>
<% end %>
</ul> 

app/views/groups/edit.html.erb
<h1>Edit <%= @group.title%>!</h1>

<%= render partial: "layouts/errors", locals: {object: @group} %>

<%= render partial: "groups", locals: {object: @group} %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<%= form_with url: "/search", local: true, method: :get do |form| %>
  <%= form.label :query, "Search for:" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>

<ul>
<% @groups.each do |group| %>
    <li> Title: <%= link_to group.title, group_path(group) %> - Created by: <%= group.user.username%></li><br><br>
<% end %>
</ul> 

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render partial: "layouts/errors", locals: {object: @group} %>

<%= render partial: "groups", locals: {object: @group} %>

app/views/groups/search.html.erb
<h1>Search Results:</h1>

<% if @groups.empty? %>
    <b><em>This Group does not exist!</b></em>
    
<% else %>
    <ul>
    <% @groups.each do |group| %>
        <li> Title: <%= link_to group.title, group_path(group) %> - Created by: <%= group.user.username%></li><br><br>
    <% end %>
    </ul>
<% end %>

app/views/groups/show.html.erb
<h1>Welcome to <%= @group.title %> </h1>


<h2>Description: </h2>
<p><%= @group.description %></p>

<h2>Rules: </h2>

<ul>
    <b><li><%= @group.rules %></li>
</ul>


<h2>Group Moderator: </h2>

<ul>
    <b><li><%= @group.user.username %></li>
</ul>

<% if @group.user == current_user %>
<h4><%= link_to "Edit Group", edit_group_path(@group)%></h4>
<% end %>

<% if !@group.topics.empty? %>
  <p><%= link_to 'See all topics', group_topics_path(@group)%></p>
  <h4>Most Recent Topics:</h4>
  <% @group.topics.order(updated_at: :desc).limit(3).each do |c|%>
    <li>
      <strong><%= c.user.username%></strong> created a topic to discuss: <%= link_to c.title, group_topic_path(@group,c)%>
    </li>
  <% end %>
<% end %>
<br>
<br>
<br>
<br>

<%= link_to "Add a Topic", new_group_topic_path(@group) %> |
<%= link_to "Add a Meetup", new_group_meeting_path(@group) %> | 
<%= link_to "All Group Meetings", group_meetings_path(@group) %> | 