config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/search' => 'groups#search'

  get '/groups' => 'groups#discover'
  
  resources :users do 
    resources :groups, only: [:new, :create, :index]
  end
  
  resources :groups do 
    resources :topics
  end
  resources :topics

  resources :meetings
  
  resources :groups do
    resources :meetings
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :groups
    has_many :topics
    has_many :topic_groups, through: :topics, source: :group

    has_secure_password

    validates :username, :email, :password, presence: true

    def self.from_omniauth(auth)
        where(email: auth.info.email).first_or_initialize do |user|
          user.username = auth.info.first_name
          user.email = auth.info.email
          user.password = SecureRandom.hex
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        @groups = @user.groups
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :username)
    end
end

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user, url: '/signup') do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>

    <%= f.label :email %>
    <%= f.email_field :email %>
    <br>
    <br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>
    
    <%= f.submit 'Submit'%>

<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>

<p>Your groups: </p>

<ul>
    <% @groups.each do |group| %>
    <li> <%= link_to group.title, group_path(group) %></li><br>
<% end %>
</ul>