config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/search' => 'groups#search'

  get '/groups' => 'groups#discover'
  
  resources :users do 
    resources :groups, only: [:new, :create, :index]
  end
  
  resources :groups do 
    resources :topics
  end
  resources :topics

  resources :meetings
  
  resources :groups do
    resources :meetings
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grouper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in?%>
    <%= link_to 'Create Group', new_user_group_path(current_user) %> |
    <%= link_to 'My Groups', user_groups_path(current_user) %> |
    <%= link_to 'Discover Groups', groups_path %> |
    <%= link_to 'Discover Meetups', meetings_path %> |
    <%= link_to 'Logout', logout_path, method:"delete"%> 
    
    <% else %>
    <%= link_to 'Signup', signup_path%> | 
    <%= link_to 'Log In With Google', '/auth/google_oauth2', method: :post %> |
    <%= link_to 'Login', login_path%> |
    
    <% end %>
  

  <div>
    <% if flash[:message] %>
      <%= flash[:message] %>
    <% end %>
    <%= @error %>
  </div>
    <%= yield %>
  </body>
</html>